import R from 'ramda';

export const lName = R.lensProp('name');
export const lOpts = R.lensProp('opts');
export const lArgs = R.lensProp('args');
export const lDir = R.lensProp('dir');
export const lAuthor = R.lensProp('author');
export const lVersion = R.lensProp('version');
export const lDescription = R.lensProp('description');
export const lKeywords = R.lensProp('keywords');
export const lLicense = R.lensProp('license');
export const lCwd = R.lensProp('cwd');
export const lType = R.lensProp('type');
export const lFile = R.lensProp('file');
export const lEntry = R.lensProp('entry');
export const lEnv = R.lensProp('env');
export const lOutput = R.lensProp('output');
export const lPath = R.lensProp('path');
export const lFilename = R.lensProp('filename');
export const lModifier = R.lensProp('modifier');
