sudo: required
language: node_js

node_js:
  - stable

addons:
  chrome: stable
  sauce_connect: true

before_install:
  - yarn global add greenkeeper-lockfile@2

before_script:
  - npx lerna bootstrap
  - npx lerna run build
  - greenkeeper-lockfile-update

script:
  - travis_retry yarn test

after_script:
  - greenkeeper-lockfile-upload
