sudo: false
language: node_js

node_js:
  - stable

addons:
  chrome: stable
  sauce_connect: true

before_install:
  - npm i -g greenkeeper-lockfile@1

before_script:
  - npx lerna bootstrap
  - npx lerna run build
  - greenkeeper-lockfile-update

script:
  - travis_retry npx lerna run test --concurrency 1

after_script:
  - greenkeeper-lockfile-upload
