language: node_js

node_js:
  - 13

jobs:
  include:

env:
  - BROOKJS_SUITE=unit
  - BROOKJS_SUITE=js
  - BROOKJS_SUITE=ts

before_install:
  - |
    if [[ $BROOKJS_SUITE == 'unit' ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
      chmod +x ./cc-test-reporter;
    fi

before_script:
  - yarn build
  - if [[ $BROOKJS_SUITE == 'js' ]]; then cd packages/brookjs-cli && node package-project.mjs --js && cd .. && cd ..; fi
  - if [[ $BROOKJS_SUITE == 'ts' ]]; then cd packages/brookjs-cli && node package-project.mjs --ts && cd .. && cd ..; fi

script:
  - yarn $BROOKJS_SUITE

after_script:
  - |
    if [[ $BROOKJS_SUITE == 'unit' ]]; then
      for PKG in brookjs-cli brookjs-desalinate brookjs-eddy brookjs-flow brookjs-silt
      do
        ./cc-test-reporter format-coverage $PWD/packages/$PKG/coverage/lcov.info --input-type lcov \
          --output $PWD/coverage/codeclimate.$PKG.json \
          --prefix $PWD/packages/$PKG;
      done
      ./cc-test-reporter sum-coverage --output - --parts 5 $PWD/coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage --input -;
    fi
